### PR TITLE
Use PlayerDB.co for name lookups

### LINKED ISSUE #59: Mojang Deprecated APIs (NameFetcher)
Confirmed by this bug report on https://github.com/minecrafter/RedisBungee/issues/82

https://help.minecraft.net/hc/en-us/articles/8969841895693-Username-History-API-Removal-FAQ-

API was declared removed somewhere in September

### PR DESCRIPTION
**Pull request by Techdaan**
I noticed that currently name lookups for UUIDs that are not cached, are not supported in RedisBungee due to Mojang removing name history.

When looking at the usages, RedisBungee internally only uses the current name (So no need for full name historyy), so I moved name lookups to [PlayerDB](https://playerdb.co/), which does not have API rate limits unlike Mojang's API.

Due to removing the `NameFetcher#nameHistoryFromUuid`, this might break backwards compatibility, but it should be easy to re-add the method and throw an exception like it does now.

closes #59

### CODE REVIEW

File: RedisBungee-API/src/main/java/com/imaginarycode/minecraft/redisbungee/api/util/uuid/NameFetcher.java [hunk 1]
```diff
@@ -11,50 +11,37 @@
...
-//        List<Name> names = gson.fromJson(response, listType);
-//
-//        List<String> humanNames = new ArrayList<>();
-//        for (Name name : names) {
-//            humanNames.add(name.name);
-//        }
-//        return humanNames;
-    }
+    public static String getName(UUID uuid) throws IOException {
+        String url = "https://playerdb.co/api/player/minecraft/" + uuid.toString();
```
Comment (ham1255) [inline RedisBungee-API/src/main/java/com/imaginarycode/minecraft/redisbungee/api/util/uuid/NameFetcher.java:31]: api here does not need removal of dashes like old mojang one?

**Review by ham1255 — APPROVED** [review]

**Comment by ham1255** [comment]
before merging, does this api provider need any kind of tos agreement?

**Comment by Techdaan** [comment]
Yeah, I don't think there's any TOS agreements but I did forget to set an user agent.

Do you have any suggestions for the `User-Agent` header? Since this is a form, `RedisBungee` might be too vague, perhaps something like `RedisBungee-ProxioDev`?

**Comment by ham1255** [comment]
One you suggested seems to be great

**Comment by Techdaan** [comment]
I just made the change, I haven't tested it yet though because I am currently busy with some other things. If you want to, I can make sure there's no errors when lookups are made later.

**Review by ham1255 — APPROVED** [review]

**Comment by ham1255** [comment]
Done some testing it seems like its working and fetches the name perfectly.

fixes: #59

**Comment by ham1255** [comment]
before merging this you can include this code in name fetcher class to maintain compatibility .
```java
public static List<String> nameHistoryFromUuid(UUID uuid) throws IOException {
        String name = getName(uuid);
        if (name == null) return Collections.emptyList();
        return Collections.singletonList(name);
    }
```

**Comment by Techdaan** [comment]
Heyhey, I missed your message earlier. I just added that snippet :)
